apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: yolo
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        # Docker Hub image for frontend
        image: snngure/yoloip2-frontend:v1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        env:
        - name: REACT_APP_BACKEND_URL
          value: http://backend:5000
